name: Manual run

on:
  workflow_dispatch:
    inputs:
      start:
        required: true
        type: string
        description: 'Start time (YYYY-MM-DD format)'
      end:  
        required: true
        type: string
        description: 'End time (YYYY-MM-DD format)'

jobs:
  manual-run:
    uses: ./.github/workflows/run.yaml
    with:
      START_DATE: ${{ inputs.start }}
      END_DATE: ${{ inputs.end }}
