name: Pull Request
on: pull_request

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
        shell: bash
      - uses: docker://rhysd/actionlint:1.6.25
        with:
          args: -color

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.0.11
      - run: bun install
      - run: bun run test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Screenshots
          path: ./screenshots
          retention-days: 3
